'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Megaphone, RefreshCw } from 'lucide-react';

type Account = { id: string; platform: string; username: string; nickname: string | null; status: string };
type ContentItem = { id: string; title: string; status: string };
type Campaign = { id: string; name: string; status: string; accountIds: string[]; contentIds: string[]; schedule: string | null; dailyLimit: number; totalJobs: number; successJobs: number; failedJobs: number };
const apiUrl = process.env.NEXT_PUBLIC_API_URL || '';

export default function CampaignsPage() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [content, setContent] = useState<ContentItem[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [campaignResponse, accountResponse, contentResponse] = await Promise.all([fetch(`${apiUrl}/api/v1/campaigns`, { cache: 'no-store' }), fetch(`${apiUrl}/api/v1/accounts`, { cache: 'no-store' }), fetch(`${apiUrl}/api/v1/content`, { cache: 'no-store' })]); const [campaignData, accountData, contentData] = await Promise.all([campaignResponse.json(), accountResponse.json(), contentResponse.json()]); if (!campaignResponse.ok) throw new Error(campaignData.message); setCampaigns(campaignData || []); setAccounts(accountData.data || []); setContent(contentData.data || []); } catch (error) { setMessage(error instanceof Error ? error.message : 'โหลดข้อมูลไม่สำเร็จ'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const payload = { name: data.get('name'), description: data.get('description'), accountIds: data.getAll('accountIds'), contentIds: data.getAll('contentIds'), schedule: data.get('schedule') || null, dailyLimit: Number(data.get('dailyLimit') || 1), status: 'DRAFT' }; try { const response = await fetch(`${apiUrl}/api/v1/campaigns`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); form.reset(); setMessage('สร้าง Campaign แบบ DRAFT สำเร็จ'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'สร้าง Campaign ไม่สำเร็จ'); } }
  async function launch(id: string) { setMessage('กำลังสร้าง Job...'); try { const response = await fetch(`${apiUrl}/api/v1/campaigns/${id}/launch`, { method: 'POST' }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setMessage(`สร้าง ${result.jobs.length} Job และส่งเข้าคิวแล้ว`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'เริ่ม Campaign ไม่สำเร็จ'); } }
  return <div className="space-y-6"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-bold font-mono text-white">CAMPAIGNS</h1><p className="text-sm text-gray-400">จับคู่คลิป ช่อง และกำหนดเวลาทำงาน</p></div><button className="btn-outline" onClick={() => void load()}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button></header>
    <form className="card grid gap-4 lg:grid-cols-2" onSubmit={submit}><input className="input-field" name="name" required placeholder="ชื่อ Campaign"/><input className="input-field" name="description" placeholder="รายละเอียด"/><div><label className="text-xs text-gray-400">เลือกช่อง (กด Ctrl เพื่อเลือกหลายรายการ)</label><select className="input-field mt-1 min-h-32" name="accountIds" multiple required>{accounts.map(item => <option value={item.id} key={item.id}>{item.platform} — {item.nickname || item.username}</option>)}</select></div><div><label className="text-xs text-gray-400">เลือก Content</label><select className="input-field mt-1 min-h-32" name="contentIds" multiple required>{content.filter(item => item.status === 'READY').map(item => <option value={item.id} key={item.id}>{item.title}</option>)}</select></div><input className="input-field" name="schedule" type="datetime-local"/><input className="input-field" name="dailyLimit" type="number" min="1" defaultValue="1"/><button className="btn-primary flex items-center justify-center gap-2 lg:col-span-2"><Megaphone className="h-4 w-4"/>สร้าง Campaign</button></form>
    {message && <div className="card text-sm text-cyber-blue">{message}</div>}
    <div className="grid gap-4 lg:grid-cols-2">{campaigns.map(item => <article className="card" key={item.id}><div className="flex items-start justify-between"><div><h2 className="font-mono text-white">{item.name}</h2><p className="mt-1 text-xs text-gray-500">{item.accountIds.length} ช่อง · {item.contentIds.length} Content</p></div><span className={`badge ${item.status === 'RUNNING' ? 'badge-busy' : 'badge-info'}`}>{item.status}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded bg-navy-700 p-2"><strong className="block text-white">{item.totalJobs}</strong>Jobs</div><div className="rounded bg-navy-700 p-2"><strong className="block text-status-green">{item.successJobs}</strong>Success</div><div className="rounded bg-navy-700 p-2"><strong className="block text-error-red">{item.failedJobs}</strong>Failed</div></div>{item.status === 'DRAFT' && <button className="btn-primary mt-4 w-full" onClick={() => void launch(item.id)}>ตรวจและส่งเข้าคิว</button>}</article>)}</div>
  </div>;
}
